
services:
  rin:
    build: .
    volumes:
      - ./storage.db:/app/storage.db
      - ./config.toml:/app/config.toml
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - AUTHOR_ID=
      - DISCORD_TOKEN=
      - SONARR_API_KEY=
      - SONARR_URL=https://sonarr.example
      - FOOTER_URL=your.url
      - OPEN_WEATHER_MAP_API_KEY=
      - KICK_CLIENT_ID=
      - KICK_CLIENT_SECRET=
      # Currently only ollama.
      - LOCALAI_URL=https://ollama.example
      - SHOKO_SERVER_API_KEY=
      - SHOKO_SERVER_URL=https://shoko-server.example
      - SERVE_STATIC_URL=https://static.example
